version: "3"
services:
  inv_sig_helper:
    build:
      context: .
      dockerfile: Dockerfile
    # image: quay.io/invidious/inv-sig-helper:latest
    container_name: sig-helper-1
    #init: true
    command: ["--tcp", "0.0.0.0:12999"]
    ports:
      - 0.0.0.0:12999:12999
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    user: 10001:10001
    security_opt:
      - no-new-privileges:true
