name: Build and test inv_sig_helper

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'docker-compose.yml'
  pull_request:
    branches: [ "master" ]
  schedule:
    # every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:  # Allow manual triggering of the workflow
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test server
      run: target/debug/inv_sig_helper_rust --test
